name: CI + Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # removido cache para evitar conflitos

      - name: Instalar dependências (forçar instalação limpa)
        run: npm install --force

      - name: Rodar ESLint
        run: npx next lint --dir .

      - name: Rodar testes
        run: npm run test

      - name: Build da aplicação
        run: npm run build
        env:
          NODE_ENV: production

      - name: Deploy para Vercel (apenas em push)
        if: github.event_name == 'push'
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
